import Foundation

/// The Tinted Theming scheme files backing ``EditorColorPreset``.
///
/// Embedded as source because `swift build` doesn't copy
/// `Bundle.module` resource bundles into the app.
///
/// Generated by scripts/update-schemes.swift; do not edit the scheme
/// text by hand.
///
/// Source: https://github.com/tinted-theming/schemes (MIT license)
enum BundledSchemes {
  /// Scheme YAML text, keyed by ``EditorColorPreset/fileName``.
  static let yamlByFileName: [String: String] = [
    "default-dark": """
    system: "base16"
    name: "Default Dark"
    author: "Chris Kempson (http://chriskempson.com)"
    variant: "dark"
    palette:
      base00: "#181818"
      base01: "#282828"
      base02: "#383838"
      base03: "#585858"
      base04: "#b8b8b8"
      base05: "#d8d8d8"
      base06: "#e8e8e8"
      base07: "#f8f8f8"
      base08: "#ab4642"
      base09: "#dc9656"
      base0A: "#f7ca88"
      base0B: "#a1b56c"
      base0C: "#86c1b9"
      base0D: "#7cafc2"
      base0E: "#ba8baf"
      base0F: "#a16946"

    """,

    "default-light": """
    system: "base16"
    name: "Default Light"
    author: "Chris Kempson (http://chriskempson.com)"
    variant: "light"
    palette:
      base00: "#f8f8f8"
      base01: "#e8e8e8"
      base02: "#d8d8d8"
      base03: "#b8b8b8"
      base04: "#585858"
      base05: "#383838"
      base06: "#282828"
      base07: "#181818"
      base08: "#ab4642"
      base09: "#dc9656"
      base0A: "#f7ca88"
      base0B: "#a1b56c"
      base0C: "#86c1b9"
      base0D: "#7cafc2"
      base0E: "#ba8baf"
      base0F: "#a16946"

    """,

    "solarized-dark": """
    system: "base16"
    name: "Solarized Dark"
    author: "Ethan Schoonover (modified by aramisgithub)"
    variant: "dark"
    palette:
      base00: "#002b36"
      base01: "#073642"
      base02: "#586e75"
      base03: "#657b83"
      base04: "#839496"
      base05: "#93a1a1"
      base06: "#eee8d5"
      base07: "#fdf6e3"
      base08: "#dc322f"
      base09: "#cb4b16"
      base0A: "#b58900"
      base0B: "#859900"
      base0C: "#2aa198"
      base0D: "#268bd2"
      base0E: "#6c71c4"
      base0F: "#d33682"

    """,

    "solarized-light": """
    system: "base16"
    name: "Solarized Light"
    author: "Ethan Schoonover (modified by aramisgithub)"
    variant: "light"
    palette:
      base00: "#fdf6e3"
      base01: "#eee8d5"
      base02: "#93a1a1"
      base03: "#839496"
      base04: "#657b83"
      base05: "#586e75"
      base06: "#073642"
      base07: "#002b36"
      base08: "#dc322f"
      base09: "#cb4b16"
      base0A: "#b58900"
      base0B: "#859900"
      base0C: "#2aa198"
      base0D: "#268bd2"
      base0E: "#6c71c4"
      base0F: "#d33682"

    """,

    "gruvbox-dark": """
    scheme:
      system: "tinted8"
      supports:
        styling-spec: "0.2.0"
      author: "Tinted Theming (https://github.com/tinted-theming)"
      theme-author: "morhetz (https://github.com/morhetz/gruvbox)"
      family: "Gruvbox"
      style: "Dark"
    variant: "dark"
    palette:
      black: "#282828"
      white: "#ebdbb2"
      red: "#cc241d"
      yellow: "#d79921"
      green: "#98971a"
      cyan: "#689d6a"
      blue: "#458588"
      magenta: "#b16286"
      gray: "#928374"
      orange: "#d65d0e"
      black-bright: "#3c3836"
      white-bright: "#fbf1c7"
      red-bright: "#fb4934"
      yellow-bright: "#fabd2f"
      green-bright: "#b8bb26"
      cyan-bright: "#8ec07c"
      blue-bright: "#83a598"
      magenta-bright: "#d3869b"
      gray-bright: "#a89984"
      orange-bright: "#fe8019"
      black-dim: "#1d2021"
      gray-dim: "#928374"
    syntax:
      entity.name: "#98971a"
      keyword: "#d79921"
      storage: "#d65d0e"
      support.constant: "#689d6a"
      entity.name.function: "#689d6a"

    """,

    "gruvbox-light": """
    system: "base24"
    name: "Gruvbox Light"
    author: "Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)"
    variant: "light"
    palette:
      base00: "#fbf1c7"
      base01: "#ebdbb2"
      base02: "#d5c4a1"
      base03: "#bdae93"
      base04: "#7c6f64"
      base05: "#3c3836"
      base06: "#282828"
      base07: "#1d2021"
      base08: "#cc241d"
      base09: "#d65d0e"
      base0A: "#d79921"
      base0B: "#98971a"
      base0C: "#689d6a"
      base0D: "#458588"
      base0E: "#b16286"
      base0F: "#9d0006"
      base10: "#f9f6d7"
      base11: "#fbf9e4"
      base12: "#9d0006"
      base13: "#b57614"
      base14: "#79740e"
      base15: "#427b58"
      base16: "#076678"
      base17: "#8f3f71"

    """,

    "dracula": """
    system: "base24"
    name: "Dracula"
    author: "clach04 (https://github.com/clach04)"
    description: "based on https://github.com/dracula/draculatheme.com/blob/main/content/spec.mdx"
    variant: "dark"
    # https://github.com/tinted-theming/base24/blob/main/styling.md
    # https://github.com/tinted-theming/home/blob/main/styling.md
    # https://github.com/chriskempson/base16/blob/main/styling.md
    # Typically expect order of base00-base07 (dark to light versus light to dark) to differ depending on variant
    # based on https://github.com/dracula/draculatheme.com/blob/main/content/spec.mdx
    palette:
      base00: "#282a36"  # Default Background  # Dracula Background
      base01: "#21222c"  # Darker Background (Darkest Gray) (Used for status bars, line number and folding marks) # Dracula Background Dark / AnsiBlack
      base02: "#44475A"  # Selection Background (Bright Black) # Dracula Selection
      base03: "#6272a4"  # Comments, Invisibles, Line Highlighting (Grey) # Dracula Current Line / Comment / AnsiBrightBlack
      base04: "#9ea8c7"  # Dark/Light Foreground (Used for status bars) (Light Grey) # NOT a Dracula color!
      base05: "#f8f8f2"  # Default Foreground, Caret, Delimiters, Operators (Foreground) # Dracula Foreground / AnsiWhite
      base06: "#f8f8f2"  # Dark Foreground (Not often used) (White)  # TODO review, currently same as above base05
      base07: "#ffffff"  # Dark Background (Not often used) (Bright White) # Dracula AnsiBrightWhite
      # ANSI8 (without Black/White) + 2 (Orange + Dark Red/Brown)
      base08: "#ff5555"  # Red
      base09: "#FFB86C"  # Orange
      base0A: "#f1fa8c"  # Yellow
      base0B: "#50fa7b"  # Green
      base0C: "#8be9fd"  # Aqua / Cyan
      base0D: "#bd93f9"  # Blue
      base0E: "#ff79c6"  # Purple / Magenta
      base0F: "#993333"  # Dark Red or Brown, derive dark red from base08 - derived via https://www.color-hex.com/color/ff5555
      # ANSI16 Bright/Bold (without Black/White)
      base10: "#1e2029"  # (Darker Black)	Darker Background - NOT a Dracula color!
      base11: "#16171d"  # (Darkest Black)	The Darkest Background - NOT a Dracula color!
      base12: "#ff6e6e"  # Bright Red
      base13: "#ffffa5"  # Bright Yellow
      base14: "#69ff94"  # Bright Green
      base15: "#a4ffff"  # Bright Cyan
      base16: "#d6acff"  # Bright Blue
      base17: "#ff92df"  # Bright Magenta / Bright Purple

    """,

    "nord": """
    scheme:
      system: "tinted8"
      supports:
        styling-spec: "0.2.0"
      name: "Nord"
      author: "Tinted Theming (https://github.com/tinted-theming)"
      theme-author: "Arctic Ice Studio (https://www.nordtheme.com)"
    variant: "dark"
    palette:
      black: "#2e3440"
      red: "#bf616a"
      yellow: "#ebcb8b"
      green: "#a3be8c"
      cyan: "#88c0d0"
      blue: "#81a1c1"
      magenta: "#b48ead"
      white: "#e5e9f0"
      orange: "#d08770"
      gray: "#616E88"
      white-dim: "#d8dee9"
      white-bright: "#eceff4"
      blue-dim: "#5e81ac"
    syntax:
      comment: "#616E88"
      constant: "#88c0d0"
      constant.numeric: "#b48ead"
      entity.name: "#81a1c1"
      entity.name.function: "#88c0d0"
      entity.name.type: "#e5e9f0"
      keyword: "#81a1c1"
      storage: "#81a1c1"
      variable.language: "#81a1c1"
      string: "#a3be8c"
      punctuation.definition.string: "#e5e9f0"
      punctuation.definition.comment: "#616E88"
      punctuation.section: "#88c0d0"
      meta.annotation: "#e5e9f0"
      meta.object: "#e5e9f0"
    ui:
      indent-guide:
        background: "#434c5e"
        active-background: "#616E88"
      highlight:
        line:
          background: "#434c5e"
      border.normal: "#3b4252"
      gutter:
        foreground: "#434c5e"
      status.info: "#ebcb8b"
      accent.normal: "#88c0d0"

    """,

    "nord-light": """
    system: "base16"
    name: "Nord Light"
    author: "threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs)"
    variant: "light"
    palette:
      base00: "#e5e9f0"
      base01: "#c2d0e7"
      base02: "#b8c5db"
      base03: "#aebacf"
      base04: "#60728c"
      base05: "#2e3440"
      base06: "#3b4252"
      base07: "#29838d"
      base08: "#99324b"
      base09: "#ac4426"
      base0A: "#9a7500"
      base0B: "#4f894c"
      base0C: "#398eac"
      base0D: "#3b6ea8"
      base0E: "#97365b"
      base0F: "#5272af"

    """,

  ]
}
