#!/usr/bin/env swift
// Downloads the Tinted Theming scheme files and regenerates
// Sources/Crumpet/Editor/BundledSchemes.swift. Each entry is <system>/<slug>;
// the file is embedded under the key <slug>, which is the name
// EditorColorPreset.fileName refers to.
//
// Usage: axo presets:update
//        SCHEMES_REF=<branch-or-tag> swift scripts/update-schemes.swift

import Foundation

let ref = ProcessInfo.processInfo.environment["SCHEMES_REF"] ?? "HEAD"
let base = "https://raw.githubusercontent.com/tinted-theming/schemes/\(ref)"

struct Scheme {
  let system: String
  let slug: String
}

let schemes = [
  Scheme(system: "base16", slug: "default-dark"),
  Scheme(system: "base16", slug: "default-light"),
  // The base24 Solarized files are terminal palettes with an unreadable
  // base05 on the light background.
  Scheme(system: "base16", slug: "solarized-dark"),
  Scheme(system: "base16", slug: "solarized-light"),
  Scheme(system: "tinted8", slug: "gruvbox-dark"),
  Scheme(system: "base24", slug: "gruvbox-light"),
  Scheme(system: "base24", slug: "dracula"),
  Scheme(system: "tinted8", slug: "nord"),
  Scheme(system: "base16", slug: "nord-light"),
]

func fetch(_ path: String) -> String {
  let url = URL(string: "\(base)/\(path)")!
  guard let data = try? Data(contentsOf: url), let text = String(data: data, encoding: .utf8)
  else {
    fatalError("failed to download \(url)")
  }
  return text
}

/// Wraps `text` in a Swift raw multiline string literal, indented by
/// `indent`. Uses enough `#` delimiters to avoid clashing with the content.
func rawMultilineLiteral(_ text: String, indent: String) -> String {
  var hashes = ""
  while text.contains("\"\"\"\(hashes)") { hashes += "#" }
  let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
  var result = "\(hashes)\"\"\"\n"
  for line in lines {
    result += line.isEmpty ? "\n" : "\(indent)\(line)\n"
  }
  result += "\(indent)\"\"\"\(hashes)"
  return result
}

let header = """
  import Foundation

  /// The Tinted Theming scheme files backing ``EditorColorPreset``.
  ///
  /// Embedded as source because `swift build` doesn't copy
  /// `Bundle.module` resource bundles into the app.
  ///
  /// Generated by scripts/update-schemes.swift; do not edit the scheme
  /// text by hand.
  ///
  /// Source: https://github.com/tinted-theming/schemes (MIT license)
  enum BundledSchemes {
    /// Scheme YAML text, keyed by ``EditorColorPreset/fileName``.
    static let yamlByFileName: [String: String] = [

  """

var output = header
for scheme in schemes {
  let yaml = fetch("\(scheme.system)/\(scheme.slug).yaml")
  FileHandle.standardError.write("\(scheme.system)/\(scheme.slug)\n".data(using: .utf8)!)
  output += "    \"\(scheme.slug)\": \(rawMultilineLiteral(yaml, indent: "      ")),\n\n"
}
output += "  ]\n}\n"

let dest =
  URL(fileURLWithPath: #filePath)
  .deletingLastPathComponent()
  .deletingLastPathComponent()
  .appendingPathComponent("Sources/Crumpet/Editor/BundledSchemes.swift")
try! output.write(to: dest, atomically: true, encoding: .utf8)
